<a href="https://colab.research.google.com/github/chaeyeon2367/ML-python-studyML/blob/main/1_NBayesModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Naive Bayes Model

# 1. Gaussian Naive Bayes

- Import data,module

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [2]:
import pandas as pd

In [3]:
iris = datasets.load_iris()
df_X=pd.DataFrame(iris.data)
df_Y=pd.DataFrame(iris.target)

In [4]:
df_X.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [5]:
df_Y.head()

0
0  0
1  0
2  0
3  0
4  0

- Fit the model

In [6]:
gnb=GaussianNB()
fitted=gnb.fit(iris.data,iris.target)
y_pred=fitted.predict(iris.data)

In [7]:
fitted.predict_proba(iris.data)[[1,48,51,100]]

array([[1.00000000e+000, 1.51480769e-017, 2.34820051e-025],
       [1.00000000e+000, 2.63876217e-018, 2.79566024e-025],
       [7.27347795e-102, 9.45169639e-001, 5.48303606e-002],
       [3.23245181e-254, 6.35381031e-011, 1.00000000e+000]])

In [8]:
fitted.predict(iris.data)[[1,48,51,100]]

array([0, 0, 1, 2])

- Confusion matrix 

In [9]:
from sklearn.metrics import confusion_matrix

In [10]:
confusion_matrix(iris.target,y_pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]])

- Setting Prior 

In [11]:
gnb2=GaussianNB(priors=[1/100,1/100,98/100])
fitted2=gnb2.fit(iris.data,iris.target)
y_pred2=fitted2.predict(iris.data)
confusion_matrix(iris.target,y_pred2)

array([[50,  0,  0],
       [ 0, 33, 17],
       [ 0,  0, 50]])

In [12]:
gnb2=GaussianNB(priors=[1/100,98/100,1/100])
fitted2=gnb2.fit(iris.data,iris.target)
y_pred2=fitted2.predict(iris.data)
confusion_matrix(iris.target,y_pred2)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0, 14, 36]])

# 2. Multinomial naive bayes

- Import modules, data

In [13]:
from sklearn.naive_bayes import MultinomialNB

In [14]:
import numpy as np

In [15]:
X = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])

In [16]:
X

array([[1, 3, 2, 2, 1, 0, 3, 2, 1, 3, 0, 2, 1, 0, 2, 3, 4, 0, 4, 2, 0, 1,
        2, 0, 0, 3, 4, 3, 1, 3, 3, 1, 3, 1, 4, 3, 0, 2, 4, 4, 3, 0, 0, 0,
        1, 3, 0, 1, 4, 3, 1, 0, 0, 0, 3, 3, 1, 3, 2, 1, 0, 0, 1, 4, 1, 1,
        4, 4, 3, 1, 0, 0, 1, 4, 0, 0, 2, 0, 0, 2, 4, 1, 1, 0, 3, 0, 0, 1,
        3, 0, 2, 3, 3, 1, 0, 0, 2, 2, 4, 1],
       [4, 2, 3, 1, 3, 3, 2, 2, 4, 3, 2, 1, 3, 1, 0, 4, 3, 4, 4, 4, 1, 2,
        0, 1, 1, 4, 0, 1, 2, 3, 1, 1, 4, 3, 2, 2, 4, 1, 0, 0, 4, 4, 0, 2,
        0, 4, 0, 0, 2, 3, 1, 0, 1, 0, 1, 0, 3, 3, 3, 3, 0, 0, 1, 3, 1, 2,
        3, 3, 1, 4, 2, 3, 2, 4, 2, 1, 0, 3, 0, 0, 4, 2, 1, 2, 1, 0, 2, 3,
        3, 1, 2, 1, 0, 0, 3, 3, 1, 0, 0, 3],
       [1, 1, 4, 0, 4, 1, 2, 0, 4, 3, 1, 4, 2, 3, 3, 2, 1, 0, 3, 0, 1, 3,
        0, 0, 3, 3, 2, 1, 4, 3, 2, 0, 3, 1, 3, 3, 1, 2, 0, 0, 0, 1, 0, 0,
        2, 1, 0, 4, 1, 0, 2, 1, 1, 3, 0, 3, 4, 4, 0, 3, 3, 2, 2, 0, 1, 0,
        3, 3, 4, 3, 3, 4, 0, 2, 3, 0, 0, 0, 4, 0, 2, 1, 1, 0, 3, 1, 2, 4,
        0, 0, 2, 4, 2,

In [17]:
y

array([1, 2, 3, 4, 5, 6])

- Creating a Multinomial naive bays Model

In [18]:
clf = MultinomialNB()
clf.fit(X, y)

MultinomialNB()

In [19]:
print(clf.predict(X[2:3]))

[3]


In [20]:
clf.predict_proba(X[2:3])

array([[2.18309830e-36, 2.02229366e-33, 1.00000000e+00, 3.58908419e-34,
        1.99633373e-45, 7.90233808e-34]])

- change the priority

In [21]:
clf2 = MultinomialNB(class_prior=[0.1,0.5,0.1,0.1,0.1,0.1])
clf2.fit(X, y)

MultinomialNB(class_prior=[0.1, 0.5, 0.1, 0.1, 0.1, 0.1])

In [22]:
clf2.predict_proba(X[2:3])

array([[2.18309830e-36, 1.01114683e-32, 1.00000000e+00, 3.58908419e-34,
        1.99633373e-45, 7.90233808e-34]])